// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 物品类型枚举
type ItemType int32

const (
	ItemType_ITEM_TYPE_UNSPECIFIED ItemType = 0
	ItemType_ITEM_TYPE_WEAPON      ItemType = 1 // 武器
	ItemType_ITEM_TYPE_ARMOR       ItemType = 2 // 护甲
	ItemType_ITEM_TYPE_ACCESSORY   ItemType = 3 // 饰品
	ItemType_ITEM_TYPE_CONSUMABLE  ItemType = 4 // 消耗品
	ItemType_ITEM_TYPE_MATERIAL    ItemType = 5 // 材料
	ItemType_ITEM_TYPE_QUEST       ItemType = 6 // 任务物品
	ItemType_ITEM_TYPE_CURRENCY    ItemType = 7 // 货币
	ItemType_ITEM_TYPE_SPECIAL     ItemType = 8 // 特殊物品
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ITEM_TYPE_UNSPECIFIED",
		1: "ITEM_TYPE_WEAPON",
		2: "ITEM_TYPE_ARMOR",
		3: "ITEM_TYPE_ACCESSORY",
		4: "ITEM_TYPE_CONSUMABLE",
		5: "ITEM_TYPE_MATERIAL",
		6: "ITEM_TYPE_QUEST",
		7: "ITEM_TYPE_CURRENCY",
		8: "ITEM_TYPE_SPECIAL",
	}
	ItemType_value = map[string]int32{
		"ITEM_TYPE_UNSPECIFIED": 0,
		"ITEM_TYPE_WEAPON":      1,
		"ITEM_TYPE_ARMOR":       2,
		"ITEM_TYPE_ACCESSORY":   3,
		"ITEM_TYPE_CONSUMABLE":  4,
		"ITEM_TYPE_MATERIAL":    5,
		"ITEM_TYPE_QUEST":       6,
		"ITEM_TYPE_CURRENCY":    7,
		"ITEM_TYPE_SPECIAL":     8,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

// 技能类型枚举
type SkillType int32

const (
	SkillType_SKILL_TYPE_UNSPECIFIED SkillType = 0
	SkillType_SKILL_TYPE_ATTACK      SkillType = 1 // 攻击技能
	SkillType_SKILL_TYPE_DEFENSE     SkillType = 2 // 防御技能
	SkillType_SKILL_TYPE_HEAL        SkillType = 3 // 治疗技能
	SkillType_SKILL_TYPE_BUFF        SkillType = 4 // 增益技能
	SkillType_SKILL_TYPE_DEBUFF      SkillType = 5 // 减益技能
	SkillType_SKILL_TYPE_PASSIVE     SkillType = 6 // 被动技能
	SkillType_SKILL_TYPE_ULTIMATE    SkillType = 7 // 终极技能
)

// Enum value maps for SkillType.
var (
	SkillType_name = map[int32]string{
		0: "SKILL_TYPE_UNSPECIFIED",
		1: "SKILL_TYPE_ATTACK",
		2: "SKILL_TYPE_DEFENSE",
		3: "SKILL_TYPE_HEAL",
		4: "SKILL_TYPE_BUFF",
		5: "SKILL_TYPE_DEBUFF",
		6: "SKILL_TYPE_PASSIVE",
		7: "SKILL_TYPE_ULTIMATE",
	}
	SkillType_value = map[string]int32{
		"SKILL_TYPE_UNSPECIFIED": 0,
		"SKILL_TYPE_ATTACK":      1,
		"SKILL_TYPE_DEFENSE":     2,
		"SKILL_TYPE_HEAL":        3,
		"SKILL_TYPE_BUFF":        4,
		"SKILL_TYPE_DEBUFF":      5,
		"SKILL_TYPE_PASSIVE":     6,
		"SKILL_TYPE_ULTIMATE":    7,
	}
)

func (x SkillType) Enum() *SkillType {
	p := new(SkillType)
	*p = x
	return p
}

func (x SkillType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SkillType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[1].Descriptor()
}

func (SkillType) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[1]
}

func (x SkillType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SkillType.Descriptor instead.
func (SkillType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

// 聊天频道枚举
type ChatChannel int32

const (
	ChatChannel_CHAT_CHANNEL_UNSPECIFIED ChatChannel = 0
	ChatChannel_CHAT_CHANNEL_WORLD       ChatChannel = 1 // 世界频道
	ChatChannel_CHAT_CHANNEL_GUILD       ChatChannel = 2 // 公会频道
	ChatChannel_CHAT_CHANNEL_TEAM        ChatChannel = 3 // 队伍频道
	ChatChannel_CHAT_CHANNEL_PRIVATE     ChatChannel = 4 // 私聊频道
	ChatChannel_CHAT_CHANNEL_SYSTEM      ChatChannel = 5 // 系统频道
	ChatChannel_CHAT_CHANNEL_TRADE       ChatChannel = 6 // 交易频道
	ChatChannel_CHAT_CHANNEL_HELP        ChatChannel = 7 // 帮助频道
)

// Enum value maps for ChatChannel.
var (
	ChatChannel_name = map[int32]string{
		0: "CHAT_CHANNEL_UNSPECIFIED",
		1: "CHAT_CHANNEL_WORLD",
		2: "CHAT_CHANNEL_GUILD",
		3: "CHAT_CHANNEL_TEAM",
		4: "CHAT_CHANNEL_PRIVATE",
		5: "CHAT_CHANNEL_SYSTEM",
		6: "CHAT_CHANNEL_TRADE",
		7: "CHAT_CHANNEL_HELP",
	}
	ChatChannel_value = map[string]int32{
		"CHAT_CHANNEL_UNSPECIFIED": 0,
		"CHAT_CHANNEL_WORLD":       1,
		"CHAT_CHANNEL_GUILD":       2,
		"CHAT_CHANNEL_TEAM":        3,
		"CHAT_CHANNEL_PRIVATE":     4,
		"CHAT_CHANNEL_SYSTEM":      5,
		"CHAT_CHANNEL_TRADE":       6,
		"CHAT_CHANNEL_HELP":        7,
	}
)

func (x ChatChannel) Enum() *ChatChannel {
	p := new(ChatChannel)
	*p = x
	return p
}

func (x ChatChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[2].Descriptor()
}

func (ChatChannel) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[2]
}

func (x ChatChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatChannel.Descriptor instead.
func (ChatChannel) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

// 任务状态枚举
type QuestStatus int32

const (
	QuestStatus_QUEST_STATUS_UNSPECIFIED QuestStatus = 0
	QuestStatus_QUEST_STATUS_NOT_STARTED QuestStatus = 1 // 未开始
	QuestStatus_QUEST_STATUS_IN_PROGRESS QuestStatus = 2 // 进行中
	QuestStatus_QUEST_STATUS_COMPLETED   QuestStatus = 3 // 已完成
	QuestStatus_QUEST_STATUS_FAILED      QuestStatus = 4 // 已失败
	QuestStatus_QUEST_STATUS_CANCELLED   QuestStatus = 5 // 已取消
)

// Enum value maps for QuestStatus.
var (
	QuestStatus_name = map[int32]string{
		0: "QUEST_STATUS_UNSPECIFIED",
		1: "QUEST_STATUS_NOT_STARTED",
		2: "QUEST_STATUS_IN_PROGRESS",
		3: "QUEST_STATUS_COMPLETED",
		4: "QUEST_STATUS_FAILED",
		5: "QUEST_STATUS_CANCELLED",
	}
	QuestStatus_value = map[string]int32{
		"QUEST_STATUS_UNSPECIFIED": 0,
		"QUEST_STATUS_NOT_STARTED": 1,
		"QUEST_STATUS_IN_PROGRESS": 2,
		"QUEST_STATUS_COMPLETED":   3,
		"QUEST_STATUS_FAILED":      4,
		"QUEST_STATUS_CANCELLED":   5,
	}
)

func (x QuestStatus) Enum() *QuestStatus {
	p := new(QuestStatus)
	*p = x
	return p
}

func (x QuestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[3].Descriptor()
}

func (QuestStatus) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[3]
}

func (x QuestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestStatus.Descriptor instead.
func (QuestStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

// 任务类型枚举
type QuestType int32

const (
	QuestType_QUEST_TYPE_UNSPECIFIED QuestType = 0
	QuestType_QUEST_TYPE_MAIN        QuestType = 1 // 主线任务
	QuestType_QUEST_TYPE_SIDE        QuestType = 2 // 支线任务
	QuestType_QUEST_TYPE_DAILY       QuestType = 3 // 日常任务
	QuestType_QUEST_TYPE_WEEKLY      QuestType = 4 // 周常任务
	QuestType_QUEST_TYPE_EVENT       QuestType = 5 // 活动任务
	QuestType_QUEST_TYPE_ACHIEVEMENT QuestType = 6 // 成就任务
)

// Enum value maps for QuestType.
var (
	QuestType_name = map[int32]string{
		0: "QUEST_TYPE_UNSPECIFIED",
		1: "QUEST_TYPE_MAIN",
		2: "QUEST_TYPE_SIDE",
		3: "QUEST_TYPE_DAILY",
		4: "QUEST_TYPE_WEEKLY",
		5: "QUEST_TYPE_EVENT",
		6: "QUEST_TYPE_ACHIEVEMENT",
	}
	QuestType_value = map[string]int32{
		"QUEST_TYPE_UNSPECIFIED": 0,
		"QUEST_TYPE_MAIN":        1,
		"QUEST_TYPE_SIDE":        2,
		"QUEST_TYPE_DAILY":       3,
		"QUEST_TYPE_WEEKLY":      4,
		"QUEST_TYPE_EVENT":       5,
		"QUEST_TYPE_ACHIEVEMENT": 6,
	}
)

func (x QuestType) Enum() *QuestType {
	p := new(QuestType)
	*p = x
	return p
}

func (x QuestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[4].Descriptor()
}

func (QuestType) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[4]
}

func (x QuestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestType.Descriptor instead.
func (QuestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{4}
}

// 物品稀有度枚举
type ItemRarity int32

const (
	ItemRarity_ITEM_RARITY_UNSPECIFIED ItemRarity = 0
	ItemRarity_ITEM_RARITY_COMMON      ItemRarity = 1 // 普通
	ItemRarity_ITEM_RARITY_UNCOMMON    ItemRarity = 2 // 不常见
	ItemRarity_ITEM_RARITY_RARE        ItemRarity = 3 // 稀有
	ItemRarity_ITEM_RARITY_EPIC        ItemRarity = 4 // 史诗
	ItemRarity_ITEM_RARITY_LEGENDARY   ItemRarity = 5 // 传说
	ItemRarity_ITEM_RARITY_MYTHIC      ItemRarity = 6 // 神话
)

// Enum value maps for ItemRarity.
var (
	ItemRarity_name = map[int32]string{
		0: "ITEM_RARITY_UNSPECIFIED",
		1: "ITEM_RARITY_COMMON",
		2: "ITEM_RARITY_UNCOMMON",
		3: "ITEM_RARITY_RARE",
		4: "ITEM_RARITY_EPIC",
		5: "ITEM_RARITY_LEGENDARY",
		6: "ITEM_RARITY_MYTHIC",
	}
	ItemRarity_value = map[string]int32{
		"ITEM_RARITY_UNSPECIFIED": 0,
		"ITEM_RARITY_COMMON":      1,
		"ITEM_RARITY_UNCOMMON":    2,
		"ITEM_RARITY_RARE":        3,
		"ITEM_RARITY_EPIC":        4,
		"ITEM_RARITY_LEGENDARY":   5,
		"ITEM_RARITY_MYTHIC":      6,
	}
)

func (x ItemRarity) Enum() *ItemRarity {
	p := new(ItemRarity)
	*p = x
	return p
}

func (x ItemRarity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemRarity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[5].Descriptor()
}

func (ItemRarity) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[5]
}

func (x ItemRarity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemRarity.Descriptor instead.
func (ItemRarity) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{5}
}

// 通用响应结构
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 通用请求结构
type CommonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonRequest) Reset() {
	*x = CommonRequest{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRequest) ProtoMessage() {}

func (x *CommonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRequest.ProtoReflect.Descriptor instead.
func (*CommonRequest) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *CommonRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommonRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CommonRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 分页信息
type PaginationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationInfo) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationInfo) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// 位置信息
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 玩家基础信息
type PlayerBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Experience    int32                  `protobuf:"varint,4,opt,name=experience,proto3" json:"experience,omitempty"`
	Position      *Position              `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	LastLogin     int64                  `protobuf:"varint,6,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBasicInfo) Reset() {
	*x = PlayerBasicInfo{}
	mi := &file_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBasicInfo) ProtoMessage() {}

func (x *PlayerBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBasicInfo.ProtoReflect.Descriptor instead.
func (*PlayerBasicInfo) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerBasicInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerBasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerBasicInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerBasicInfo) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *PlayerBasicInfo) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerBasicInfo) GetLastLogin() int64 {
	if x != nil {
		return x.LastLogin
	}
	return 0
}

func (x *PlayerBasicInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 服务器信息
type ServerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	MaxPlayers     int32                  `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	CurrentPlayers int32                  `protobuf:"varint,5,opt,name=current_players,json=currentPlayers,proto3" json:"current_players,omitempty"`
	IsOnline       bool                   `protobuf:"varint,6,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *ServerInfo) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *ServerInfo) GetCurrentPlayers() int32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *ServerInfo) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\x14greatestworks.common\"v\n" +
	"\x0eCommonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xd8\x01\n" +
	"\rCommonRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12M\n" +
	"\bmetadata\x18\x03 \x03(\v21.greatestworks.common.CommonRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\x0ePaginationInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"4\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"\xf2\x01\n" +
	"\x0fPlayerBasicInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\x04 \x01(\x05R\n" +
	"experience\x12:\n" +
	"\bposition\x18\x05 \x01(\v2\x1e.greatestworks.common.PositionR\bposition\x12\x1d\n" +
	"\n" +
	"last_login\x18\x06 \x01(\x03R\tlastLogin\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xbe\x01\n" +
	"\n" +
	"ServerInfo\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vmax_players\x18\x04 \x01(\x05R\n" +
	"maxPlayers\x12'\n" +
	"\x0fcurrent_players\x18\x05 \x01(\x05R\x0ecurrentPlayers\x12\x1b\n" +
	"\tis_online\x18\x06 \x01(\bR\bisOnline*\xdf\x01\n" +
	"\bItemType\x12\x19\n" +
	"\x15ITEM_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ITEM_TYPE_WEAPON\x10\x01\x12\x13\n" +
	"\x0fITEM_TYPE_ARMOR\x10\x02\x12\x17\n" +
	"\x13ITEM_TYPE_ACCESSORY\x10\x03\x12\x18\n" +
	"\x14ITEM_TYPE_CONSUMABLE\x10\x04\x12\x16\n" +
	"\x12ITEM_TYPE_MATERIAL\x10\x05\x12\x13\n" +
	"\x0fITEM_TYPE_QUEST\x10\x06\x12\x16\n" +
	"\x12ITEM_TYPE_CURRENCY\x10\a\x12\x15\n" +
	"\x11ITEM_TYPE_SPECIAL\x10\b*\xc8\x01\n" +
	"\tSkillType\x12\x1a\n" +
	"\x16SKILL_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SKILL_TYPE_ATTACK\x10\x01\x12\x16\n" +
	"\x12SKILL_TYPE_DEFENSE\x10\x02\x12\x13\n" +
	"\x0fSKILL_TYPE_HEAL\x10\x03\x12\x13\n" +
	"\x0fSKILL_TYPE_BUFF\x10\x04\x12\x15\n" +
	"\x11SKILL_TYPE_DEBUFF\x10\x05\x12\x16\n" +
	"\x12SKILL_TYPE_PASSIVE\x10\x06\x12\x17\n" +
	"\x13SKILL_TYPE_ULTIMATE\x10\a*\xd4\x01\n" +
	"\vChatChannel\x12\x1c\n" +
	"\x18CHAT_CHANNEL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHAT_CHANNEL_WORLD\x10\x01\x12\x16\n" +
	"\x12CHAT_CHANNEL_GUILD\x10\x02\x12\x15\n" +
	"\x11CHAT_CHANNEL_TEAM\x10\x03\x12\x18\n" +
	"\x14CHAT_CHANNEL_PRIVATE\x10\x04\x12\x17\n" +
	"\x13CHAT_CHANNEL_SYSTEM\x10\x05\x12\x16\n" +
	"\x12CHAT_CHANNEL_TRADE\x10\x06\x12\x15\n" +
	"\x11CHAT_CHANNEL_HELP\x10\a*\xb8\x01\n" +
	"\vQuestStatus\x12\x1c\n" +
	"\x18QUEST_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18QUEST_STATUS_NOT_STARTED\x10\x01\x12\x1c\n" +
	"\x18QUEST_STATUS_IN_PROGRESS\x10\x02\x12\x1a\n" +
	"\x16QUEST_STATUS_COMPLETED\x10\x03\x12\x17\n" +
	"\x13QUEST_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16QUEST_STATUS_CANCELLED\x10\x05*\xb0\x01\n" +
	"\tQuestType\x12\x1a\n" +
	"\x16QUEST_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fQUEST_TYPE_MAIN\x10\x01\x12\x13\n" +
	"\x0fQUEST_TYPE_SIDE\x10\x02\x12\x14\n" +
	"\x10QUEST_TYPE_DAILY\x10\x03\x12\x15\n" +
	"\x11QUEST_TYPE_WEEKLY\x10\x04\x12\x14\n" +
	"\x10QUEST_TYPE_EVENT\x10\x05\x12\x1a\n" +
	"\x16QUEST_TYPE_ACHIEVEMENT\x10\x06*\xba\x01\n" +
	"\n" +
	"ItemRarity\x12\x1b\n" +
	"\x17ITEM_RARITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ITEM_RARITY_COMMON\x10\x01\x12\x18\n" +
	"\x14ITEM_RARITY_UNCOMMON\x10\x02\x12\x14\n" +
	"\x10ITEM_RARITY_RARE\x10\x03\x12\x14\n" +
	"\x10ITEM_RARITY_EPIC\x10\x04\x12\x19\n" +
	"\x15ITEM_RARITY_LEGENDARY\x10\x05\x12\x16\n" +
	"\x12ITEM_RARITY_MYTHIC\x10\x06B<Z#greatestworks/internal/proto/common\xaa\x02\x14GreatestWorks.Commonb\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_common_proto_goTypes = []any{
	(ItemType)(0),           // 0: greatestworks.common.ItemType
	(SkillType)(0),          // 1: greatestworks.common.SkillType
	(ChatChannel)(0),        // 2: greatestworks.common.ChatChannel
	(QuestStatus)(0),        // 3: greatestworks.common.QuestStatus
	(QuestType)(0),          // 4: greatestworks.common.QuestType
	(ItemRarity)(0),         // 5: greatestworks.common.ItemRarity
	(*CommonResponse)(nil),  // 6: greatestworks.common.CommonResponse
	(*CommonRequest)(nil),   // 7: greatestworks.common.CommonRequest
	(*PaginationInfo)(nil),  // 8: greatestworks.common.PaginationInfo
	(*Position)(nil),        // 9: greatestworks.common.Position
	(*PlayerBasicInfo)(nil), // 10: greatestworks.common.PlayerBasicInfo
	(*ServerInfo)(nil),      // 11: greatestworks.common.ServerInfo
	nil,                     // 12: greatestworks.common.CommonRequest.MetadataEntry
}
var file_proto_common_proto_depIdxs = []int32{
	12, // 0: greatestworks.common.CommonRequest.metadata:type_name -> greatestworks.common.CommonRequest.MetadataEntry
	9,  // 1: greatestworks.common.PlayerBasicInfo.position:type_name -> greatestworks.common.Position
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
