// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package player

import (
	"github.com/google/wire"
	"greatestworks/business/module/bag"
	"greatestworks/business/module/chat"
	"greatestworks/business/module/friend"
	"greatestworks/business/module/pet"
	"greatestworks/business/module/shop"
	"greatestworks/business/module/task"
	"greatestworks/business/module/vip"
)

// Injectors from wire.go:

func NewGamePlay() *GamePlay {
	system := friend.NewSystem()
	privateChat := chat.NewPrivateChat()
	data := task.NewTaskData()
	petSystem := pet.NewSystem()
	shopData := shop.NewData()
	bagSystem := bag.NewSystem()
	vipVip := vip.NewVip()
	gamePlay := &GamePlay{
		friendSystem: system,
		privateChat:  privateChat,
		taskData:     data,
		petSystem:    petSystem,
		shopData:     shopData,
		bagSystem:    bagSystem,
		vip:          vipVip,
	}
	return gamePlay
}

// wire.go:

var MegaSet = wire.NewSet(friend.NewSystem, chat.NewPrivateChat, task.NewTaskData, pet.NewSystem, shop.NewData, bag.NewSystem, vip.NewVip, wire.Struct(new(GamePlay), "friendSystem", "privateChat", "taskData", "petSystem", "shopData", "bagSystem", "vip"))
