version: "3.7"
services:
  mysql8019:
    image: mysql:8.0.19
    restart: "always"
    ports:
      - 13306:3306
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    # 账号密码
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "tracer"
      MYSQL_PASSWORD: "1234"
    # 文件夹以及文件映射
    volumes:
      - ./init.sql:/data/application/init.sql
  redis626:
    # 镜像版本号
    image: redis:6.2.6
    # 端口号
    ports:
      - 16379:6379
    # 失败后总是重启
    restart: "always"
    # 以配置文件的方式启动 redis.conf
    command: "redis-server /etc/redis/redis.conf --appendonly yes"
    # 文件夹以及文件映射
    volumes:
      - /Users/user/docker/data:/data
      - /Users/user/redis-6.2.6/redis.conf:/etc/redis/redis.conf
  tracer_containers:
    build: .
    restart: "always"
    # command: sh -c  "./wait-for-it.sh mysql8019:3306 -- ./tracer ./config/config.ini"  # shell脚本方式启动
    command: ["/wait-for-it.sh", "mysql8019:3306", "--", "/tracer", "config/config.ini"]
    # 依赖启动项
    depends_on:
      - mysql8019
      - redis626
    ports:
      - 8888:8000
