---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2023/2/25 12:32
---

-- 简单的 table
function TableDemo()
    mytable = {}
    print("mytable 的类型是 ",type(mytable))

    mytable[1]= "Lua"
    mytable["wow"] = "修改前"
    print("mytable 索引为 1 的元素是 ", mytable[1])
    print("mytable 索引为 wow 的元素是 ", mytable["wow"])

    -- alternatetable和mytable的是指同一个 table
    alternatetable = mytable

    print("alternatetable 索引为 1 的元素是 ", alternatetable[1])
    print("mytable 索引为 wow 的元素是 ", alternatetable["wow"])

    alternatetable["wow"] = "修改后"

    print("mytable 索引为 wow 的元素是 ", mytable["wow"])

    -- 释放变量
    alternatetable = nil
    print("alternatetable 是 ", alternatetable)

    -- mytable 仍然可以访问
    print("mytable 索引为 wow 的元素是 ", mytable["wow"])

    mytable = nil
    print("mytable 是 ", mytable)
end

TableDemo()