// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/pet.proto

package pet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "greatestworks/internal/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建宠物请求
type CreatePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SpeciesId     string                 `protobuf:"bytes,2,opt,name=species_id,json=speciesId,proto3" json:"species_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	InitialLevel  int32                  `protobuf:"varint,4,opt,name=initial_level,json=initialLevel,proto3" json:"initial_level,omitempty"`
	Rarity        string                 `protobuf:"bytes,5,opt,name=rarity,proto3" json:"rarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetRequest) Reset() {
	*x = CreatePetRequest{}
	mi := &file_proto_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetRequest) ProtoMessage() {}

func (x *CreatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetRequest.ProtoReflect.Descriptor instead.
func (*CreatePetRequest) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePetRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CreatePetRequest) GetSpeciesId() string {
	if x != nil {
		return x.SpeciesId
	}
	return ""
}

func (x *CreatePetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePetRequest) GetInitialLevel() int32 {
	if x != nil {
		return x.InitialLevel
	}
	return 0
}

func (x *CreatePetRequest) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

// 创建宠物响应
type CreatePetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *common.CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Pet           *PetInfo               `protobuf:"bytes,2,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetResponse) Reset() {
	*x = CreatePetResponse{}
	mi := &file_proto_pet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetResponse) ProtoMessage() {}

func (x *CreatePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetResponse.ProtoReflect.Descriptor instead.
func (*CreatePetResponse) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePetResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *CreatePetResponse) GetPet() *PetInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

// 获取宠物信息请求
type GetPetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetInfoRequest) Reset() {
	*x = GetPetInfoRequest{}
	mi := &file_proto_pet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetInfoRequest) ProtoMessage() {}

func (x *GetPetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{2}
}

func (x *GetPetInfoRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

// 获取宠物信息响应
type GetPetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *common.CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Pet           *PetInfo               `protobuf:"bytes,2,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetInfoResponse) Reset() {
	*x = GetPetInfoResponse{}
	mi := &file_proto_pet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetInfoResponse) ProtoMessage() {}

func (x *GetPetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{3}
}

func (x *GetPetInfoResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetPetInfoResponse) GetPet() *PetInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

// 更新宠物信息请求
type UpdatePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePetRequest) Reset() {
	*x = UpdatePetRequest{}
	mi := &file_proto_pet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetRequest) ProtoMessage() {}

func (x *UpdatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetRequest.ProtoReflect.Descriptor instead.
func (*UpdatePetRequest) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePetRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *UpdatePetRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

// 更新宠物信息响应
type UpdatePetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *common.CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Pet           *PetInfo               `protobuf:"bytes,2,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePetResponse) Reset() {
	*x = UpdatePetResponse{}
	mi := &file_proto_pet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetResponse) ProtoMessage() {}

func (x *UpdatePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetResponse.ProtoReflect.Descriptor instead.
func (*UpdatePetResponse) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePetResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *UpdatePetResponse) GetPet() *PetInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

// 宠物升级请求
type LevelUpPetRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PetId            string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	ExperiencePoints int32                  `protobuf:"varint,2,opt,name=experience_points,json=experiencePoints,proto3" json:"experience_points,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LevelUpPetRequest) Reset() {
	*x = LevelUpPetRequest{}
	mi := &file_proto_pet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelUpPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelUpPetRequest) ProtoMessage() {}

func (x *LevelUpPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelUpPetRequest.ProtoReflect.Descriptor instead.
func (*LevelUpPetRequest) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{6}
}

func (x *LevelUpPetRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *LevelUpPetRequest) GetExperiencePoints() int32 {
	if x != nil {
		return x.ExperiencePoints
	}
	return 0
}

// 宠物升级响应
type LevelUpPetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *common.CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Pet           *PetInfo               `protobuf:"bytes,2,opt,name=pet,proto3" json:"pet,omitempty"`
	LeveledUp     bool                   `protobuf:"varint,3,opt,name=leveled_up,json=leveledUp,proto3" json:"leveled_up,omitempty"`
	NewLevel      int32                  `protobuf:"varint,4,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelUpPetResponse) Reset() {
	*x = LevelUpPetResponse{}
	mi := &file_proto_pet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelUpPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelUpPetResponse) ProtoMessage() {}

func (x *LevelUpPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelUpPetResponse.ProtoReflect.Descriptor instead.
func (*LevelUpPetResponse) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{7}
}

func (x *LevelUpPetResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *LevelUpPetResponse) GetPet() *PetInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

func (x *LevelUpPetResponse) GetLeveledUp() bool {
	if x != nil {
		return x.LeveledUp
	}
	return false
}

func (x *LevelUpPetResponse) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

// 宠物进化请求
type EvolvePetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PetId           string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	TargetSpeciesId string                 `protobuf:"bytes,2,opt,name=target_species_id,json=targetSpeciesId,proto3" json:"target_species_id,omitempty"`
	RequiredItems   []string               `protobuf:"bytes,3,rep,name=required_items,json=requiredItems,proto3" json:"required_items,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EvolvePetRequest) Reset() {
	*x = EvolvePetRequest{}
	mi := &file_proto_pet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvolvePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolvePetRequest) ProtoMessage() {}

func (x *EvolvePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolvePetRequest.ProtoReflect.Descriptor instead.
func (*EvolvePetRequest) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{8}
}

func (x *EvolvePetRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *EvolvePetRequest) GetTargetSpeciesId() string {
	if x != nil {
		return x.TargetSpeciesId
	}
	return ""
}

func (x *EvolvePetRequest) GetRequiredItems() []string {
	if x != nil {
		return x.RequiredItems
	}
	return nil
}

// 宠物进化响应
type EvolvePetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *common.CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Pet           *PetInfo               `protobuf:"bytes,2,opt,name=pet,proto3" json:"pet,omitempty"`
	Evolved       bool                   `protobuf:"varint,3,opt,name=evolved,proto3" json:"evolved,omitempty"`
	NewSpecies    string                 `protobuf:"bytes,4,opt,name=new_species,json=newSpecies,proto3" json:"new_species,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvolvePetResponse) Reset() {
	*x = EvolvePetResponse{}
	mi := &file_proto_pet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvolvePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolvePetResponse) ProtoMessage() {}

func (x *EvolvePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolvePetResponse.ProtoReflect.Descriptor instead.
func (*EvolvePetResponse) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{9}
}

func (x *EvolvePetResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *EvolvePetResponse) GetPet() *PetInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

func (x *EvolvePetResponse) GetEvolved() bool {
	if x != nil {
		return x.Evolved
	}
	return false
}

func (x *EvolvePetResponse) GetNewSpecies() string {
	if x != nil {
		return x.NewSpecies
	}
	return ""
}

// 获取玩家宠物列表请求
type GetPlayerPetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerPetsRequest) Reset() {
	*x = GetPlayerPetsRequest{}
	mi := &file_proto_pet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerPetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerPetsRequest) ProtoMessage() {}

func (x *GetPlayerPetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerPetsRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerPetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlayerPetsRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetPlayerPetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPlayerPetsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// 获取玩家宠物列表响应
type GetPlayerPetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *common.CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Pets          []*PetInfo             `protobuf:"bytes,2,rep,name=pets,proto3" json:"pets,omitempty"`
	Pagination    *common.PaginationInfo `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerPetsResponse) Reset() {
	*x = GetPlayerPetsResponse{}
	mi := &file_proto_pet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerPetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerPetsResponse) ProtoMessage() {}

func (x *GetPlayerPetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerPetsResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerPetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{11}
}

func (x *GetPlayerPetsResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetPlayerPetsResponse) GetPets() []*PetInfo {
	if x != nil {
		return x.Pets
	}
	return nil
}

func (x *GetPlayerPetsResponse) GetPagination() *common.PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 宠物信息
type PetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SpeciesId     string                 `protobuf:"bytes,3,opt,name=species_id,json=speciesId,proto3" json:"species_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Experience    int32                  `protobuf:"varint,6,opt,name=experience,proto3" json:"experience,omitempty"`
	MaxExperience int32                  `protobuf:"varint,7,opt,name=max_experience,json=maxExperience,proto3" json:"max_experience,omitempty"`
	Rarity        string                 `protobuf:"bytes,8,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Stats         *PetStats              `protobuf:"bytes,9,opt,name=stats,proto3" json:"stats,omitempty"`
	Skills        *PetSkills             `protobuf:"bytes,10,opt,name=skills,proto3" json:"skills,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastFed       int64                  `protobuf:"varint,12,opt,name=last_fed,json=lastFed,proto3" json:"last_fed,omitempty"`
	IsActive      bool                   `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetInfo) Reset() {
	*x = PetInfo{}
	mi := &file_proto_pet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetInfo) ProtoMessage() {}

func (x *PetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetInfo.ProtoReflect.Descriptor instead.
func (*PetInfo) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{12}
}

func (x *PetInfo) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *PetInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PetInfo) GetSpeciesId() string {
	if x != nil {
		return x.SpeciesId
	}
	return ""
}

func (x *PetInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PetInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PetInfo) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *PetInfo) GetMaxExperience() int32 {
	if x != nil {
		return x.MaxExperience
	}
	return 0
}

func (x *PetInfo) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *PetInfo) GetStats() *PetStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *PetInfo) GetSkills() *PetSkills {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *PetInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PetInfo) GetLastFed() int64 {
	if x != nil {
		return x.LastFed
	}
	return 0
}

func (x *PetInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// 宠物属性
type PetStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        int32                  `protobuf:"varint,1,opt,name=health,proto3" json:"health,omitempty"`
	MaxHealth     int32                  `protobuf:"varint,2,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	Attack        int32                  `protobuf:"varint,3,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       int32                  `protobuf:"varint,4,opt,name=defense,proto3" json:"defense,omitempty"`
	Speed         int32                  `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Intelligence  int32                  `protobuf:"varint,6,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Loyalty       int32                  `protobuf:"varint,7,opt,name=loyalty,proto3" json:"loyalty,omitempty"`
	Happiness     int32                  `protobuf:"varint,8,opt,name=happiness,proto3" json:"happiness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetStats) Reset() {
	*x = PetStats{}
	mi := &file_proto_pet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetStats) ProtoMessage() {}

func (x *PetStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetStats.ProtoReflect.Descriptor instead.
func (*PetStats) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{13}
}

func (x *PetStats) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PetStats) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *PetStats) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *PetStats) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *PetStats) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PetStats) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *PetStats) GetLoyalty() int32 {
	if x != nil {
		return x.Loyalty
	}
	return 0
}

func (x *PetStats) GetHappiness() int32 {
	if x != nil {
		return x.Happiness
	}
	return 0
}

// 宠物技能
type PetSkills struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*PetSkill            `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	SkillPoints   int32                  `protobuf:"varint,2,opt,name=skill_points,json=skillPoints,proto3" json:"skill_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetSkills) Reset() {
	*x = PetSkills{}
	mi := &file_proto_pet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetSkills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetSkills) ProtoMessage() {}

func (x *PetSkills) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetSkills.ProtoReflect.Descriptor instead.
func (*PetSkills) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{14}
}

func (x *PetSkills) GetSkills() []*PetSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *PetSkills) GetSkillPoints() int32 {
	if x != nil {
		return x.SkillPoints
	}
	return 0
}

// 宠物技能详情
type PetSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	MaxLevel      int32                  `protobuf:"varint,5,opt,name=max_level,json=maxLevel,proto3" json:"max_level,omitempty"`
	SkillType     string                 `protobuf:"bytes,6,opt,name=skill_type,json=skillType,proto3" json:"skill_type,omitempty"`
	Cooldown      int32                  `protobuf:"varint,7,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	ManaCost      int32                  `protobuf:"varint,8,opt,name=mana_cost,json=manaCost,proto3" json:"mana_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetSkill) Reset() {
	*x = PetSkill{}
	mi := &file_proto_pet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetSkill) ProtoMessage() {}

func (x *PetSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetSkill.ProtoReflect.Descriptor instead.
func (*PetSkill) Descriptor() ([]byte, []int) {
	return file_proto_pet_proto_rawDescGZIP(), []int{15}
}

func (x *PetSkill) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *PetSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PetSkill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PetSkill) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PetSkill) GetMaxLevel() int32 {
	if x != nil {
		return x.MaxLevel
	}
	return 0
}

func (x *PetSkill) GetSkillType() string {
	if x != nil {
		return x.SkillType
	}
	return ""
}

func (x *PetSkill) GetCooldown() int32 {
	if x != nil {
		return x.Cooldown
	}
	return 0
}

func (x *PetSkill) GetManaCost() int32 {
	if x != nil {
		return x.ManaCost
	}
	return 0
}

var File_proto_pet_proto protoreflect.FileDescriptor

const file_proto_pet_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/pet.proto\x12\x11greatestworks.pet\x1a\x12proto/common.proto\"\x9f\x01\n" +
	"\x10CreatePetRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"species_id\x18\x02 \x01(\tR\tspeciesId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rinitial_level\x18\x04 \x01(\x05R\finitialLevel\x12\x16\n" +
	"\x06rarity\x18\x05 \x01(\tR\x06rarity\"\x7f\n" +
	"\x11CreatePetResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12,\n" +
	"\x03pet\x18\x02 \x01(\v2\x1a.greatestworks.pet.PetInfoR\x03pet\"*\n" +
	"\x11GetPetInfoRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\"\x80\x01\n" +
	"\x12GetPetInfoResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12,\n" +
	"\x03pet\x18\x02 \x01(\v2\x1a.greatestworks.pet.PetInfoR\x03pet\"\xb1\x01\n" +
	"\x10UpdatePetRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12J\n" +
	"\aupdates\x18\x02 \x03(\v20.greatestworks.pet.UpdatePetRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x11UpdatePetResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12,\n" +
	"\x03pet\x18\x02 \x01(\v2\x1a.greatestworks.pet.PetInfoR\x03pet\"W\n" +
	"\x11LevelUpPetRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12+\n" +
	"\x11experience_points\x18\x02 \x01(\x05R\x10experiencePoints\"\xbc\x01\n" +
	"\x12LevelUpPetResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12,\n" +
	"\x03pet\x18\x02 \x01(\v2\x1a.greatestworks.pet.PetInfoR\x03pet\x12\x1d\n" +
	"\n" +
	"leveled_up\x18\x03 \x01(\bR\tleveledUp\x12\x1b\n" +
	"\tnew_level\x18\x04 \x01(\x05R\bnewLevel\"|\n" +
	"\x10EvolvePetRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12*\n" +
	"\x11target_species_id\x18\x02 \x01(\tR\x0ftargetSpeciesId\x12%\n" +
	"\x0erequired_items\x18\x03 \x03(\tR\rrequiredItems\"\xba\x01\n" +
	"\x11EvolvePetResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12,\n" +
	"\x03pet\x18\x02 \x01(\v2\x1a.greatestworks.pet.PetInfoR\x03pet\x12\x18\n" +
	"\aevolved\x18\x03 \x01(\bR\aevolved\x12\x1f\n" +
	"\vnew_species\x18\x04 \x01(\tR\n" +
	"newSpecies\"a\n" +
	"\x14GetPlayerPetsRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xcb\x01\n" +
	"\x15GetPlayerPetsResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12.\n" +
	"\x04pets\x18\x02 \x03(\v2\x1a.greatestworks.pet.PetInfoR\x04pets\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.greatestworks.common.PaginationInfoR\n" +
	"pagination\"\xa5\x03\n" +
	"\aPetInfo\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"species_id\x18\x03 \x01(\tR\tspeciesId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\x06 \x01(\x05R\n" +
	"experience\x12%\n" +
	"\x0emax_experience\x18\a \x01(\x05R\rmaxExperience\x12\x16\n" +
	"\x06rarity\x18\b \x01(\tR\x06rarity\x121\n" +
	"\x05stats\x18\t \x01(\v2\x1b.greatestworks.pet.PetStatsR\x05stats\x124\n" +
	"\x06skills\x18\n" +
	" \x01(\v2\x1c.greatestworks.pet.PetSkillsR\x06skills\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x19\n" +
	"\blast_fed\x18\f \x01(\x03R\alastFed\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\"\xe5\x01\n" +
	"\bPetStats\x12\x16\n" +
	"\x06health\x18\x01 \x01(\x05R\x06health\x12\x1d\n" +
	"\n" +
	"max_health\x18\x02 \x01(\x05R\tmaxHealth\x12\x16\n" +
	"\x06attack\x18\x03 \x01(\x05R\x06attack\x12\x18\n" +
	"\adefense\x18\x04 \x01(\x05R\adefense\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x05R\x05speed\x12\"\n" +
	"\fintelligence\x18\x06 \x01(\x05R\fintelligence\x12\x18\n" +
	"\aloyalty\x18\a \x01(\x05R\aloyalty\x12\x1c\n" +
	"\thappiness\x18\b \x01(\x05R\thappiness\"c\n" +
	"\tPetSkills\x123\n" +
	"\x06skills\x18\x01 \x03(\v2\x1b.greatestworks.pet.PetSkillR\x06skills\x12!\n" +
	"\fskill_points\x18\x02 \x01(\x05R\vskillPoints\"\xe6\x01\n" +
	"\bPetSkill\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1b\n" +
	"\tmax_level\x18\x05 \x01(\x05R\bmaxLevel\x12\x1d\n" +
	"\n" +
	"skill_type\x18\x06 \x01(\tR\tskillType\x12\x1a\n" +
	"\bcooldown\x18\a \x01(\x05R\bcooldown\x12\x1b\n" +
	"\tmana_cost\x18\b \x01(\x05R\bmanaCost2\xae\x04\n" +
	"\n" +
	"PetService\x12V\n" +
	"\tCreatePet\x12#.greatestworks.pet.CreatePetRequest\x1a$.greatestworks.pet.CreatePetResponse\x12Y\n" +
	"\n" +
	"GetPetInfo\x12$.greatestworks.pet.GetPetInfoRequest\x1a%.greatestworks.pet.GetPetInfoResponse\x12V\n" +
	"\tUpdatePet\x12#.greatestworks.pet.UpdatePetRequest\x1a$.greatestworks.pet.UpdatePetResponse\x12Y\n" +
	"\n" +
	"LevelUpPet\x12$.greatestworks.pet.LevelUpPetRequest\x1a%.greatestworks.pet.LevelUpPetResponse\x12V\n" +
	"\tEvolvePet\x12#.greatestworks.pet.EvolvePetRequest\x1a$.greatestworks.pet.EvolvePetResponse\x12b\n" +
	"\rGetPlayerPets\x12'.greatestworks.pet.GetPlayerPetsRequest\x1a(.greatestworks.pet.GetPlayerPetsResponseB6Z greatestworks/internal/proto/pet\xaa\x02\x11GreatestWorks.Petb\x06proto3"

var (
	file_proto_pet_proto_rawDescOnce sync.Once
	file_proto_pet_proto_rawDescData []byte
)

func file_proto_pet_proto_rawDescGZIP() []byte {
	file_proto_pet_proto_rawDescOnce.Do(func() {
		file_proto_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pet_proto_rawDesc), len(file_proto_pet_proto_rawDesc)))
	})
	return file_proto_pet_proto_rawDescData
}

var file_proto_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_pet_proto_goTypes = []any{
	(*CreatePetRequest)(nil),      // 0: greatestworks.pet.CreatePetRequest
	(*CreatePetResponse)(nil),     // 1: greatestworks.pet.CreatePetResponse
	(*GetPetInfoRequest)(nil),     // 2: greatestworks.pet.GetPetInfoRequest
	(*GetPetInfoResponse)(nil),    // 3: greatestworks.pet.GetPetInfoResponse
	(*UpdatePetRequest)(nil),      // 4: greatestworks.pet.UpdatePetRequest
	(*UpdatePetResponse)(nil),     // 5: greatestworks.pet.UpdatePetResponse
	(*LevelUpPetRequest)(nil),     // 6: greatestworks.pet.LevelUpPetRequest
	(*LevelUpPetResponse)(nil),    // 7: greatestworks.pet.LevelUpPetResponse
	(*EvolvePetRequest)(nil),      // 8: greatestworks.pet.EvolvePetRequest
	(*EvolvePetResponse)(nil),     // 9: greatestworks.pet.EvolvePetResponse
	(*GetPlayerPetsRequest)(nil),  // 10: greatestworks.pet.GetPlayerPetsRequest
	(*GetPlayerPetsResponse)(nil), // 11: greatestworks.pet.GetPlayerPetsResponse
	(*PetInfo)(nil),               // 12: greatestworks.pet.PetInfo
	(*PetStats)(nil),              // 13: greatestworks.pet.PetStats
	(*PetSkills)(nil),             // 14: greatestworks.pet.PetSkills
	(*PetSkill)(nil),              // 15: greatestworks.pet.PetSkill
	nil,                           // 16: greatestworks.pet.UpdatePetRequest.UpdatesEntry
	(*common.CommonResponse)(nil), // 17: greatestworks.common.CommonResponse
	(*common.PaginationInfo)(nil), // 18: greatestworks.common.PaginationInfo
}
var file_proto_pet_proto_depIdxs = []int32{
	17, // 0: greatestworks.pet.CreatePetResponse.common:type_name -> greatestworks.common.CommonResponse
	12, // 1: greatestworks.pet.CreatePetResponse.pet:type_name -> greatestworks.pet.PetInfo
	17, // 2: greatestworks.pet.GetPetInfoResponse.common:type_name -> greatestworks.common.CommonResponse
	12, // 3: greatestworks.pet.GetPetInfoResponse.pet:type_name -> greatestworks.pet.PetInfo
	16, // 4: greatestworks.pet.UpdatePetRequest.updates:type_name -> greatestworks.pet.UpdatePetRequest.UpdatesEntry
	17, // 5: greatestworks.pet.UpdatePetResponse.common:type_name -> greatestworks.common.CommonResponse
	12, // 6: greatestworks.pet.UpdatePetResponse.pet:type_name -> greatestworks.pet.PetInfo
	17, // 7: greatestworks.pet.LevelUpPetResponse.common:type_name -> greatestworks.common.CommonResponse
	12, // 8: greatestworks.pet.LevelUpPetResponse.pet:type_name -> greatestworks.pet.PetInfo
	17, // 9: greatestworks.pet.EvolvePetResponse.common:type_name -> greatestworks.common.CommonResponse
	12, // 10: greatestworks.pet.EvolvePetResponse.pet:type_name -> greatestworks.pet.PetInfo
	17, // 11: greatestworks.pet.GetPlayerPetsResponse.common:type_name -> greatestworks.common.CommonResponse
	12, // 12: greatestworks.pet.GetPlayerPetsResponse.pets:type_name -> greatestworks.pet.PetInfo
	18, // 13: greatestworks.pet.GetPlayerPetsResponse.pagination:type_name -> greatestworks.common.PaginationInfo
	13, // 14: greatestworks.pet.PetInfo.stats:type_name -> greatestworks.pet.PetStats
	14, // 15: greatestworks.pet.PetInfo.skills:type_name -> greatestworks.pet.PetSkills
	15, // 16: greatestworks.pet.PetSkills.skills:type_name -> greatestworks.pet.PetSkill
	0,  // 17: greatestworks.pet.PetService.CreatePet:input_type -> greatestworks.pet.CreatePetRequest
	2,  // 18: greatestworks.pet.PetService.GetPetInfo:input_type -> greatestworks.pet.GetPetInfoRequest
	4,  // 19: greatestworks.pet.PetService.UpdatePet:input_type -> greatestworks.pet.UpdatePetRequest
	6,  // 20: greatestworks.pet.PetService.LevelUpPet:input_type -> greatestworks.pet.LevelUpPetRequest
	8,  // 21: greatestworks.pet.PetService.EvolvePet:input_type -> greatestworks.pet.EvolvePetRequest
	10, // 22: greatestworks.pet.PetService.GetPlayerPets:input_type -> greatestworks.pet.GetPlayerPetsRequest
	1,  // 23: greatestworks.pet.PetService.CreatePet:output_type -> greatestworks.pet.CreatePetResponse
	3,  // 24: greatestworks.pet.PetService.GetPetInfo:output_type -> greatestworks.pet.GetPetInfoResponse
	5,  // 25: greatestworks.pet.PetService.UpdatePet:output_type -> greatestworks.pet.UpdatePetResponse
	7,  // 26: greatestworks.pet.PetService.LevelUpPet:output_type -> greatestworks.pet.LevelUpPetResponse
	9,  // 27: greatestworks.pet.PetService.EvolvePet:output_type -> greatestworks.pet.EvolvePetResponse
	11, // 28: greatestworks.pet.PetService.GetPlayerPets:output_type -> greatestworks.pet.GetPlayerPetsResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_pet_proto_init() }
func file_proto_pet_proto_init() {
	if File_proto_pet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pet_proto_rawDesc), len(file_proto_pet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pet_proto_goTypes,
		DependencyIndexes: file_proto_pet_proto_depIdxs,
		MessageInfos:      file_proto_pet_proto_msgTypes,
	}.Build()
	File_proto_pet_proto = out.File
	file_proto_pet_proto_goTypes = nil
	file_proto_pet_proto_depIdxs = nil
}
