---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2023/2/25 12:20
---


print("Hello World！")

function ForExample()
    tab1 = { key1 = "val11", key2 = "val22", "val33" }
    for k, v in pairs(tab1) do
        print(k .. " - " .. v)
    end

    tab1.key1 = nil
    for k, v in pairs(tab1) do
        print(k .. " - " .. v)
    end
end

ForExample()



