// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/player.proto

package player

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "greatestworks/internal/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家性别枚举
type PlayerGender int32

const (
	PlayerGender_PLAYER_GENDER_UNSPECIFIED PlayerGender = 0
	PlayerGender_PLAYER_GENDER_MALE        PlayerGender = 1 // 男性
	PlayerGender_PLAYER_GENDER_FEMALE      PlayerGender = 2 // 女性
	PlayerGender_PLAYER_GENDER_OTHER       PlayerGender = 3 // 其他
)

// Enum value maps for PlayerGender.
var (
	PlayerGender_name = map[int32]string{
		0: "PLAYER_GENDER_UNSPECIFIED",
		1: "PLAYER_GENDER_MALE",
		2: "PLAYER_GENDER_FEMALE",
		3: "PLAYER_GENDER_OTHER",
	}
	PlayerGender_value = map[string]int32{
		"PLAYER_GENDER_UNSPECIFIED": 0,
		"PLAYER_GENDER_MALE":        1,
		"PLAYER_GENDER_FEMALE":      2,
		"PLAYER_GENDER_OTHER":       3,
	}
)

func (x PlayerGender) Enum() *PlayerGender {
	p := new(PlayerGender)
	*p = x
	return p
}

func (x PlayerGender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerGender) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_player_proto_enumTypes[0].Descriptor()
}

func (PlayerGender) Type() protoreflect.EnumType {
	return &file_proto_player_proto_enumTypes[0]
}

func (x PlayerGender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerGender.Descriptor instead.
func (PlayerGender) EnumDescriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{0}
}

// 玩家职业枚举
type PlayerClass int32

const (
	PlayerClass_PLAYER_CLASS_UNSPECIFIED PlayerClass = 0
	PlayerClass_PLAYER_CLASS_WARRIOR     PlayerClass = 1 // 战士
	PlayerClass_PLAYER_CLASS_MAGE        PlayerClass = 2 // 法师
	PlayerClass_PLAYER_CLASS_ARCHER      PlayerClass = 3 // 弓箭手
	PlayerClass_PLAYER_CLASS_ASSASSIN    PlayerClass = 4 // 刺客
	PlayerClass_PLAYER_CLASS_PRIEST      PlayerClass = 5 // 牧师
	PlayerClass_PLAYER_CLASS_PALADIN     PlayerClass = 6 // 圣骑士
	PlayerClass_PLAYER_CLASS_DRUID       PlayerClass = 7 // 德鲁伊
	PlayerClass_PLAYER_CLASS_NECROMANCER PlayerClass = 8 // 死灵法师
)

// Enum value maps for PlayerClass.
var (
	PlayerClass_name = map[int32]string{
		0: "PLAYER_CLASS_UNSPECIFIED",
		1: "PLAYER_CLASS_WARRIOR",
		2: "PLAYER_CLASS_MAGE",
		3: "PLAYER_CLASS_ARCHER",
		4: "PLAYER_CLASS_ASSASSIN",
		5: "PLAYER_CLASS_PRIEST",
		6: "PLAYER_CLASS_PALADIN",
		7: "PLAYER_CLASS_DRUID",
		8: "PLAYER_CLASS_NECROMANCER",
	}
	PlayerClass_value = map[string]int32{
		"PLAYER_CLASS_UNSPECIFIED": 0,
		"PLAYER_CLASS_WARRIOR":     1,
		"PLAYER_CLASS_MAGE":        2,
		"PLAYER_CLASS_ARCHER":      3,
		"PLAYER_CLASS_ASSASSIN":    4,
		"PLAYER_CLASS_PRIEST":      5,
		"PLAYER_CLASS_PALADIN":     6,
		"PLAYER_CLASS_DRUID":       7,
		"PLAYER_CLASS_NECROMANCER": 8,
	}
)

func (x PlayerClass) Enum() *PlayerClass {
	p := new(PlayerClass)
	*p = x
	return p
}

func (x PlayerClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerClass) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_player_proto_enumTypes[1].Descriptor()
}

func (PlayerClass) Type() protoreflect.EnumType {
	return &file_proto_player_proto_enumTypes[1]
}

func (x PlayerClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerClass.Descriptor instead.
func (PlayerClass) EnumDescriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{1}
}

// 玩家等级枚举
type PlayerLevel int32

const (
	PlayerLevel_PLAYER_LEVEL_UNSPECIFIED  PlayerLevel = 0
	PlayerLevel_PLAYER_LEVEL_BEGINNER     PlayerLevel = 1 // 新手
	PlayerLevel_PLAYER_LEVEL_INTERMEDIATE PlayerLevel = 2 // 中级
	PlayerLevel_PLAYER_LEVEL_ADVANCED     PlayerLevel = 3 // 高级
	PlayerLevel_PLAYER_LEVEL_EXPERT       PlayerLevel = 4 // 专家
	PlayerLevel_PLAYER_LEVEL_MASTER       PlayerLevel = 5 // 大师
	PlayerLevel_PLAYER_LEVEL_GRANDMASTER  PlayerLevel = 6 // 宗师
)

// Enum value maps for PlayerLevel.
var (
	PlayerLevel_name = map[int32]string{
		0: "PLAYER_LEVEL_UNSPECIFIED",
		1: "PLAYER_LEVEL_BEGINNER",
		2: "PLAYER_LEVEL_INTERMEDIATE",
		3: "PLAYER_LEVEL_ADVANCED",
		4: "PLAYER_LEVEL_EXPERT",
		5: "PLAYER_LEVEL_MASTER",
		6: "PLAYER_LEVEL_GRANDMASTER",
	}
	PlayerLevel_value = map[string]int32{
		"PLAYER_LEVEL_UNSPECIFIED":  0,
		"PLAYER_LEVEL_BEGINNER":     1,
		"PLAYER_LEVEL_INTERMEDIATE": 2,
		"PLAYER_LEVEL_ADVANCED":     3,
		"PLAYER_LEVEL_EXPERT":       4,
		"PLAYER_LEVEL_MASTER":       5,
		"PLAYER_LEVEL_GRANDMASTER":  6,
	}
)

func (x PlayerLevel) Enum() *PlayerLevel {
	p := new(PlayerLevel)
	*p = x
	return p
}

func (x PlayerLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_player_proto_enumTypes[2].Descriptor()
}

func (PlayerLevel) Type() protoreflect.EnumType {
	return &file_proto_player_proto_enumTypes[2]
}

func (x PlayerLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerLevel.Descriptor instead.
func (PlayerLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{2}
}

// 玩家状态枚举
type PlayerStatus int32

const (
	PlayerStatus_PLAYER_STATUS_UNSPECIFIED PlayerStatus = 0
	PlayerStatus_PLAYER_STATUS_OFFLINE     PlayerStatus = 1 // 离线
	PlayerStatus_PLAYER_STATUS_ONLINE      PlayerStatus = 2 // 在线
	PlayerStatus_PLAYER_STATUS_IN_BATTLE   PlayerStatus = 3 // 战斗中
	PlayerStatus_PLAYER_STATUS_IN_QUEUE    PlayerStatus = 4 // 排队中
	PlayerStatus_PLAYER_STATUS_AFK         PlayerStatus = 5 // 离开
	PlayerStatus_PLAYER_STATUS_BANNED      PlayerStatus = 6 // 被封禁
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "PLAYER_STATUS_UNSPECIFIED",
		1: "PLAYER_STATUS_OFFLINE",
		2: "PLAYER_STATUS_ONLINE",
		3: "PLAYER_STATUS_IN_BATTLE",
		4: "PLAYER_STATUS_IN_QUEUE",
		5: "PLAYER_STATUS_AFK",
		6: "PLAYER_STATUS_BANNED",
	}
	PlayerStatus_value = map[string]int32{
		"PLAYER_STATUS_UNSPECIFIED": 0,
		"PLAYER_STATUS_OFFLINE":     1,
		"PLAYER_STATUS_ONLINE":      2,
		"PLAYER_STATUS_IN_BATTLE":   3,
		"PLAYER_STATUS_IN_QUEUE":    4,
		"PLAYER_STATUS_AFK":         5,
		"PLAYER_STATUS_BANNED":      6,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_player_proto_enumTypes[3].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_proto_player_proto_enumTypes[3]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{3}
}

// 创建玩家请求
type CreatePlayerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AccountId       string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	InitialLevel    int32                  `protobuf:"varint,3,opt,name=initial_level,json=initialLevel,proto3" json:"initial_level,omitempty"`
	InitialPosition *common.Position       `protobuf:"bytes,4,opt,name=initial_position,json=initialPosition,proto3" json:"initial_position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePlayerRequest) Reset() {
	*x = CreatePlayerRequest{}
	mi := &file_proto_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerRequest) ProtoMessage() {}

func (x *CreatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlayerRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreatePlayerRequest) GetInitialLevel() int32 {
	if x != nil {
		return x.InitialLevel
	}
	return 0
}

func (x *CreatePlayerRequest) GetInitialPosition() *common.Position {
	if x != nil {
		return x.InitialPosition
	}
	return nil
}

// 创建玩家响应
type CreatePlayerResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Common        *common.CommonResponse  `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Player        *common.PlayerBasicInfo `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerResponse) Reset() {
	*x = CreatePlayerResponse{}
	mi := &file_proto_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerResponse) ProtoMessage() {}

func (x *CreatePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerResponse.ProtoReflect.Descriptor instead.
func (*CreatePlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlayerResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *CreatePlayerResponse) GetPlayer() *common.PlayerBasicInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

// 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientVersion string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

// 登录响应
type LoginResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Common        *common.CommonResponse  `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Player        *common.PlayerBasicInfo `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	SessionToken  string                  `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	LoginTime     int64                   `protobuf:"varint,4,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *LoginResponse) GetPlayer() *common.PlayerBasicInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *LoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *LoginResponse) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

// 登出请求
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LogoutRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 登出响应
type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *common.CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	LogoutTime    int64                  `protobuf:"varint,2,opt,name=logout_time,json=logoutTime,proto3" json:"logout_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *LogoutResponse) GetLogoutTime() int64 {
	if x != nil {
		return x.LogoutTime
	}
	return 0
}

// 获取玩家信息请求
type GetPlayerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoRequest) Reset() {
	*x = GetPlayerInfoRequest{}
	mi := &file_proto_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoRequest) ProtoMessage() {}

func (x *GetPlayerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlayerInfoRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// 获取玩家信息响应
type GetPlayerInfoResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Common        *common.CommonResponse  `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Player        *common.PlayerBasicInfo `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	Stats         *PlayerStats            `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	Inventory     *PlayerInventory        `protobuf:"bytes,4,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoResponse) Reset() {
	*x = GetPlayerInfoResponse{}
	mi := &file_proto_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoResponse) ProtoMessage() {}

func (x *GetPlayerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlayerInfoResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetPlayerInfoResponse) GetPlayer() *common.PlayerBasicInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *GetPlayerInfoResponse) GetStats() *PlayerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetPlayerInfoResponse) GetInventory() *PlayerInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

// 更新玩家信息请求
type UpdatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Updates       map[string]string      `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerRequest) Reset() {
	*x = UpdatePlayerRequest{}
	mi := &file_proto_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerRequest) ProtoMessage() {}

func (x *UpdatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *UpdatePlayerRequest) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

// 更新玩家信息响应
type UpdatePlayerResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Common        *common.CommonResponse  `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Player        *common.PlayerBasicInfo `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerResponse) Reset() {
	*x = UpdatePlayerResponse{}
	mi := &file_proto_player_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerResponse) ProtoMessage() {}

func (x *UpdatePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePlayerResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *UpdatePlayerResponse) GetPlayer() *common.PlayerBasicInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

// 移动玩家请求
type MovePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Position      *common.Position       `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	SceneId       string                 `protobuf:"bytes,3,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePlayerRequest) Reset() {
	*x = MovePlayerRequest{}
	mi := &file_proto_player_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePlayerRequest) ProtoMessage() {}

func (x *MovePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePlayerRequest.ProtoReflect.Descriptor instead.
func (*MovePlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{10}
}

func (x *MovePlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MovePlayerRequest) GetPosition() *common.Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MovePlayerRequest) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

// 移动玩家响应
type MovePlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Common        *common.CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	NewPosition   *common.Position       `protobuf:"bytes,2,opt,name=new_position,json=newPosition,proto3" json:"new_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePlayerResponse) Reset() {
	*x = MovePlayerResponse{}
	mi := &file_proto_player_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePlayerResponse) ProtoMessage() {}

func (x *MovePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePlayerResponse.ProtoReflect.Descriptor instead.
func (*MovePlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{11}
}

func (x *MovePlayerResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *MovePlayerResponse) GetNewPosition() *common.Position {
	if x != nil {
		return x.NewPosition
	}
	return nil
}

// 获取在线玩家列表请求
type GetOnlinePlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlinePlayersRequest) Reset() {
	*x = GetOnlinePlayersRequest{}
	mi := &file_proto_player_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlinePlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlinePlayersRequest) ProtoMessage() {}

func (x *GetOnlinePlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlinePlayersRequest.ProtoReflect.Descriptor instead.
func (*GetOnlinePlayersRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{12}
}

func (x *GetOnlinePlayersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOnlinePlayersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// 获取在线玩家列表响应
type GetOnlinePlayersResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Common        *common.CommonResponse    `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Players       []*common.PlayerBasicInfo `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Pagination    *common.PaginationInfo    `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlinePlayersResponse) Reset() {
	*x = GetOnlinePlayersResponse{}
	mi := &file_proto_player_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlinePlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlinePlayersResponse) ProtoMessage() {}

func (x *GetOnlinePlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlinePlayersResponse.ProtoReflect.Descriptor instead.
func (*GetOnlinePlayersResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{13}
}

func (x *GetOnlinePlayersResponse) GetCommon() *common.CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *GetOnlinePlayersResponse) GetPlayers() []*common.PlayerBasicInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GetOnlinePlayersResponse) GetPagination() *common.PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 玩家属性
type PlayerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        int32                  `protobuf:"varint,1,opt,name=health,proto3" json:"health,omitempty"`
	MaxHealth     int32                  `protobuf:"varint,2,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	Mana          int32                  `protobuf:"varint,3,opt,name=mana,proto3" json:"mana,omitempty"`
	MaxMana       int32                  `protobuf:"varint,4,opt,name=max_mana,json=maxMana,proto3" json:"max_mana,omitempty"`
	Attack        int32                  `protobuf:"varint,5,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       int32                  `protobuf:"varint,6,opt,name=defense,proto3" json:"defense,omitempty"`
	Speed         int32                  `protobuf:"varint,7,opt,name=speed,proto3" json:"speed,omitempty"`
	Gold          int32                  `protobuf:"varint,8,opt,name=gold,proto3" json:"gold,omitempty"`
	Diamonds      int32                  `protobuf:"varint,9,opt,name=diamonds,proto3" json:"diamonds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStats) Reset() {
	*x = PlayerStats{}
	mi := &file_proto_player_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStats) ProtoMessage() {}

func (x *PlayerStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStats.ProtoReflect.Descriptor instead.
func (*PlayerStats) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerStats) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PlayerStats) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *PlayerStats) GetMana() int32 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *PlayerStats) GetMaxMana() int32 {
	if x != nil {
		return x.MaxMana
	}
	return 0
}

func (x *PlayerStats) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *PlayerStats) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *PlayerStats) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PlayerStats) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlayerStats) GetDiamonds() int32 {
	if x != nil {
		return x.Diamonds
	}
	return 0
}

// 玩家背包
type PlayerInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      int32                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	UsedSlots     int32                  `protobuf:"varint,2,opt,name=used_slots,json=usedSlots,proto3" json:"used_slots,omitempty"`
	Items         []*InventoryItem       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInventory) Reset() {
	*x = PlayerInventory{}
	mi := &file_proto_player_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInventory) ProtoMessage() {}

func (x *PlayerInventory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInventory.ProtoReflect.Descriptor instead.
func (*PlayerInventory) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerInventory) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *PlayerInventory) GetUsedSlots() int32 {
	if x != nil {
		return x.UsedSlots
	}
	return 0
}

func (x *PlayerInventory) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 背包物品
type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MaxStack      int32                  `protobuf:"varint,4,opt,name=max_stack,json=maxStack,proto3" json:"max_stack,omitempty"`
	ItemType      common.ItemType        `protobuf:"varint,5,opt,name=item_type,json=itemType,proto3,enum=greatestworks.common.ItemType" json:"item_type,omitempty"`
	Rarity        common.ItemRarity      `protobuf:"varint,6,opt,name=rarity,proto3,enum=greatestworks.common.ItemRarity" json:"rarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_proto_player_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{16}
}

func (x *InventoryItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InventoryItem) GetMaxStack() int32 {
	if x != nil {
		return x.MaxStack
	}
	return 0
}

func (x *InventoryItem) GetItemType() common.ItemType {
	if x != nil {
		return x.ItemType
	}
	return common.ItemType(0)
}

func (x *InventoryItem) GetRarity() common.ItemRarity {
	if x != nil {
		return x.Rarity
	}
	return common.ItemRarity(0)
}

var File_proto_player_proto protoreflect.FileDescriptor

const file_proto_player_proto_rawDesc = "" +
	"\n" +
	"\x12proto/player.proto\x12\x14greatestworks.player\x1a\x12proto/common.proto\"\xb8\x01\n" +
	"\x13CreatePlayerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12#\n" +
	"\rinitial_level\x18\x03 \x01(\x05R\finitialLevel\x12I\n" +
	"\x10initial_position\x18\x04 \x01(\v2\x1e.greatestworks.common.PositionR\x0finitialPosition\"\x93\x01\n" +
	"\x14CreatePlayerResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12=\n" +
	"\x06player\x18\x02 \x01(\v2%.greatestworks.common.PlayerBasicInfoR\x06player\"q\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\"\xd0\x01\n" +
	"\rLoginResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12=\n" +
	"\x06player\x18\x02 \x01(\v2%.greatestworks.common.PlayerBasicInfoR\x06player\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"login_time\x18\x04 \x01(\x03R\tloginTime\"K\n" +
	"\rLogoutRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"o\n" +
	"\x0eLogoutResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12\x1f\n" +
	"\vlogout_time\x18\x02 \x01(\x03R\n" +
	"logoutTime\"3\n" +
	"\x14GetPlayerInfoRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\x92\x02\n" +
	"\x15GetPlayerInfoResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12=\n" +
	"\x06player\x18\x02 \x01(\v2%.greatestworks.common.PlayerBasicInfoR\x06player\x127\n" +
	"\x05stats\x18\x03 \x01(\v2!.greatestworks.player.PlayerStatsR\x05stats\x12C\n" +
	"\tinventory\x18\x04 \x01(\v2%.greatestworks.player.PlayerInventoryR\tinventory\"\xc0\x01\n" +
	"\x13UpdatePlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12P\n" +
	"\aupdates\x18\x02 \x03(\v26.greatestworks.player.UpdatePlayerRequest.UpdatesEntryR\aupdates\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\x14UpdatePlayerResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12=\n" +
	"\x06player\x18\x02 \x01(\v2%.greatestworks.common.PlayerBasicInfoR\x06player\"\x87\x01\n" +
	"\x11MovePlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12:\n" +
	"\bposition\x18\x02 \x01(\v2\x1e.greatestworks.common.PositionR\bposition\x12\x19\n" +
	"\bscene_id\x18\x03 \x01(\tR\asceneId\"\x95\x01\n" +
	"\x12MovePlayerResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12A\n" +
	"\fnew_position\x18\x02 \x01(\v2\x1e.greatestworks.common.PositionR\vnewPosition\"G\n" +
	"\x17GetOnlinePlayersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xdf\x01\n" +
	"\x18GetOnlinePlayersResponse\x12<\n" +
	"\x06common\x18\x01 \x01(\v2$.greatestworks.common.CommonResponseR\x06common\x12?\n" +
	"\aplayers\x18\x02 \x03(\v2%.greatestworks.common.PlayerBasicInfoR\aplayers\x12D\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2$.greatestworks.common.PaginationInfoR\n" +
	"pagination\"\xeb\x01\n" +
	"\vPlayerStats\x12\x16\n" +
	"\x06health\x18\x01 \x01(\x05R\x06health\x12\x1d\n" +
	"\n" +
	"max_health\x18\x02 \x01(\x05R\tmaxHealth\x12\x12\n" +
	"\x04mana\x18\x03 \x01(\x05R\x04mana\x12\x19\n" +
	"\bmax_mana\x18\x04 \x01(\x05R\amaxMana\x12\x16\n" +
	"\x06attack\x18\x05 \x01(\x05R\x06attack\x12\x18\n" +
	"\adefense\x18\x06 \x01(\x05R\adefense\x12\x14\n" +
	"\x05speed\x18\a \x01(\x05R\x05speed\x12\x12\n" +
	"\x04gold\x18\b \x01(\x05R\x04gold\x12\x1a\n" +
	"\bdiamonds\x18\t \x01(\x05R\bdiamonds\"\x87\x01\n" +
	"\x0fPlayerInventory\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x05R\bcapacity\x12\x1d\n" +
	"\n" +
	"used_slots\x18\x02 \x01(\x05R\tusedSlots\x129\n" +
	"\x05items\x18\x03 \x03(\v2#.greatestworks.player.InventoryItemR\x05items\"\xec\x01\n" +
	"\rInventoryItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1b\n" +
	"\tmax_stack\x18\x04 \x01(\x05R\bmaxStack\x12;\n" +
	"\titem_type\x18\x05 \x01(\x0e2\x1e.greatestworks.common.ItemTypeR\bitemType\x128\n" +
	"\x06rarity\x18\x06 \x01(\x0e2 .greatestworks.common.ItemRarityR\x06rarity*x\n" +
	"\fPlayerGender\x12\x1d\n" +
	"\x19PLAYER_GENDER_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PLAYER_GENDER_MALE\x10\x01\x12\x18\n" +
	"\x14PLAYER_GENDER_FEMALE\x10\x02\x12\x17\n" +
	"\x13PLAYER_GENDER_OTHER\x10\x03*\xf9\x01\n" +
	"\vPlayerClass\x12\x1c\n" +
	"\x18PLAYER_CLASS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PLAYER_CLASS_WARRIOR\x10\x01\x12\x15\n" +
	"\x11PLAYER_CLASS_MAGE\x10\x02\x12\x17\n" +
	"\x13PLAYER_CLASS_ARCHER\x10\x03\x12\x19\n" +
	"\x15PLAYER_CLASS_ASSASSIN\x10\x04\x12\x17\n" +
	"\x13PLAYER_CLASS_PRIEST\x10\x05\x12\x18\n" +
	"\x14PLAYER_CLASS_PALADIN\x10\x06\x12\x16\n" +
	"\x12PLAYER_CLASS_DRUID\x10\a\x12\x1c\n" +
	"\x18PLAYER_CLASS_NECROMANCER\x10\b*\xd0\x01\n" +
	"\vPlayerLevel\x12\x1c\n" +
	"\x18PLAYER_LEVEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PLAYER_LEVEL_BEGINNER\x10\x01\x12\x1d\n" +
	"\x19PLAYER_LEVEL_INTERMEDIATE\x10\x02\x12\x19\n" +
	"\x15PLAYER_LEVEL_ADVANCED\x10\x03\x12\x17\n" +
	"\x13PLAYER_LEVEL_EXPERT\x10\x04\x12\x17\n" +
	"\x13PLAYER_LEVEL_MASTER\x10\x05\x12\x1c\n" +
	"\x18PLAYER_LEVEL_GRANDMASTER\x10\x06*\xcc\x01\n" +
	"\fPlayerStatus\x12\x1d\n" +
	"\x19PLAYER_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PLAYER_STATUS_OFFLINE\x10\x01\x12\x18\n" +
	"\x14PLAYER_STATUS_ONLINE\x10\x02\x12\x1b\n" +
	"\x17PLAYER_STATUS_IN_BATTLE\x10\x03\x12\x1a\n" +
	"\x16PLAYER_STATUS_IN_QUEUE\x10\x04\x12\x15\n" +
	"\x11PLAYER_STATUS_AFK\x10\x05\x12\x18\n" +
	"\x14PLAYER_STATUS_BANNED\x10\x062\xc2\x05\n" +
	"\rPlayerService\x12e\n" +
	"\fCreatePlayer\x12).greatestworks.player.CreatePlayerRequest\x1a*.greatestworks.player.CreatePlayerResponse\x12P\n" +
	"\x05Login\x12\".greatestworks.player.LoginRequest\x1a#.greatestworks.player.LoginResponse\x12S\n" +
	"\x06Logout\x12#.greatestworks.player.LogoutRequest\x1a$.greatestworks.player.LogoutResponse\x12h\n" +
	"\rGetPlayerInfo\x12*.greatestworks.player.GetPlayerInfoRequest\x1a+.greatestworks.player.GetPlayerInfoResponse\x12e\n" +
	"\fUpdatePlayer\x12).greatestworks.player.UpdatePlayerRequest\x1a*.greatestworks.player.UpdatePlayerResponse\x12_\n" +
	"\n" +
	"MovePlayer\x12'.greatestworks.player.MovePlayerRequest\x1a(.greatestworks.player.MovePlayerResponse\x12q\n" +
	"\x10GetOnlinePlayers\x12-.greatestworks.player.GetOnlinePlayersRequest\x1a..greatestworks.player.GetOnlinePlayersResponseB<Z#greatestworks/internal/proto/player\xaa\x02\x14GreatestWorks.Playerb\x06proto3"

var (
	file_proto_player_proto_rawDescOnce sync.Once
	file_proto_player_proto_rawDescData []byte
)

func file_proto_player_proto_rawDescGZIP() []byte {
	file_proto_player_proto_rawDescOnce.Do(func() {
		file_proto_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_player_proto_rawDesc), len(file_proto_player_proto_rawDesc)))
	})
	return file_proto_player_proto_rawDescData
}

var file_proto_player_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_player_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_player_proto_goTypes = []any{
	(PlayerGender)(0),                // 0: greatestworks.player.PlayerGender
	(PlayerClass)(0),                 // 1: greatestworks.player.PlayerClass
	(PlayerLevel)(0),                 // 2: greatestworks.player.PlayerLevel
	(PlayerStatus)(0),                // 3: greatestworks.player.PlayerStatus
	(*CreatePlayerRequest)(nil),      // 4: greatestworks.player.CreatePlayerRequest
	(*CreatePlayerResponse)(nil),     // 5: greatestworks.player.CreatePlayerResponse
	(*LoginRequest)(nil),             // 6: greatestworks.player.LoginRequest
	(*LoginResponse)(nil),            // 7: greatestworks.player.LoginResponse
	(*LogoutRequest)(nil),            // 8: greatestworks.player.LogoutRequest
	(*LogoutResponse)(nil),           // 9: greatestworks.player.LogoutResponse
	(*GetPlayerInfoRequest)(nil),     // 10: greatestworks.player.GetPlayerInfoRequest
	(*GetPlayerInfoResponse)(nil),    // 11: greatestworks.player.GetPlayerInfoResponse
	(*UpdatePlayerRequest)(nil),      // 12: greatestworks.player.UpdatePlayerRequest
	(*UpdatePlayerResponse)(nil),     // 13: greatestworks.player.UpdatePlayerResponse
	(*MovePlayerRequest)(nil),        // 14: greatestworks.player.MovePlayerRequest
	(*MovePlayerResponse)(nil),       // 15: greatestworks.player.MovePlayerResponse
	(*GetOnlinePlayersRequest)(nil),  // 16: greatestworks.player.GetOnlinePlayersRequest
	(*GetOnlinePlayersResponse)(nil), // 17: greatestworks.player.GetOnlinePlayersResponse
	(*PlayerStats)(nil),              // 18: greatestworks.player.PlayerStats
	(*PlayerInventory)(nil),          // 19: greatestworks.player.PlayerInventory
	(*InventoryItem)(nil),            // 20: greatestworks.player.InventoryItem
	nil,                              // 21: greatestworks.player.UpdatePlayerRequest.UpdatesEntry
	(*common.Position)(nil),          // 22: greatestworks.common.Position
	(*common.CommonResponse)(nil),    // 23: greatestworks.common.CommonResponse
	(*common.PlayerBasicInfo)(nil),   // 24: greatestworks.common.PlayerBasicInfo
	(*common.PaginationInfo)(nil),    // 25: greatestworks.common.PaginationInfo
	(common.ItemType)(0),             // 26: greatestworks.common.ItemType
	(common.ItemRarity)(0),           // 27: greatestworks.common.ItemRarity
}
var file_proto_player_proto_depIdxs = []int32{
	22, // 0: greatestworks.player.CreatePlayerRequest.initial_position:type_name -> greatestworks.common.Position
	23, // 1: greatestworks.player.CreatePlayerResponse.common:type_name -> greatestworks.common.CommonResponse
	24, // 2: greatestworks.player.CreatePlayerResponse.player:type_name -> greatestworks.common.PlayerBasicInfo
	23, // 3: greatestworks.player.LoginResponse.common:type_name -> greatestworks.common.CommonResponse
	24, // 4: greatestworks.player.LoginResponse.player:type_name -> greatestworks.common.PlayerBasicInfo
	23, // 5: greatestworks.player.LogoutResponse.common:type_name -> greatestworks.common.CommonResponse
	23, // 6: greatestworks.player.GetPlayerInfoResponse.common:type_name -> greatestworks.common.CommonResponse
	24, // 7: greatestworks.player.GetPlayerInfoResponse.player:type_name -> greatestworks.common.PlayerBasicInfo
	18, // 8: greatestworks.player.GetPlayerInfoResponse.stats:type_name -> greatestworks.player.PlayerStats
	19, // 9: greatestworks.player.GetPlayerInfoResponse.inventory:type_name -> greatestworks.player.PlayerInventory
	21, // 10: greatestworks.player.UpdatePlayerRequest.updates:type_name -> greatestworks.player.UpdatePlayerRequest.UpdatesEntry
	23, // 11: greatestworks.player.UpdatePlayerResponse.common:type_name -> greatestworks.common.CommonResponse
	24, // 12: greatestworks.player.UpdatePlayerResponse.player:type_name -> greatestworks.common.PlayerBasicInfo
	22, // 13: greatestworks.player.MovePlayerRequest.position:type_name -> greatestworks.common.Position
	23, // 14: greatestworks.player.MovePlayerResponse.common:type_name -> greatestworks.common.CommonResponse
	22, // 15: greatestworks.player.MovePlayerResponse.new_position:type_name -> greatestworks.common.Position
	23, // 16: greatestworks.player.GetOnlinePlayersResponse.common:type_name -> greatestworks.common.CommonResponse
	24, // 17: greatestworks.player.GetOnlinePlayersResponse.players:type_name -> greatestworks.common.PlayerBasicInfo
	25, // 18: greatestworks.player.GetOnlinePlayersResponse.pagination:type_name -> greatestworks.common.PaginationInfo
	20, // 19: greatestworks.player.PlayerInventory.items:type_name -> greatestworks.player.InventoryItem
	26, // 20: greatestworks.player.InventoryItem.item_type:type_name -> greatestworks.common.ItemType
	27, // 21: greatestworks.player.InventoryItem.rarity:type_name -> greatestworks.common.ItemRarity
	4,  // 22: greatestworks.player.PlayerService.CreatePlayer:input_type -> greatestworks.player.CreatePlayerRequest
	6,  // 23: greatestworks.player.PlayerService.Login:input_type -> greatestworks.player.LoginRequest
	8,  // 24: greatestworks.player.PlayerService.Logout:input_type -> greatestworks.player.LogoutRequest
	10, // 25: greatestworks.player.PlayerService.GetPlayerInfo:input_type -> greatestworks.player.GetPlayerInfoRequest
	12, // 26: greatestworks.player.PlayerService.UpdatePlayer:input_type -> greatestworks.player.UpdatePlayerRequest
	14, // 27: greatestworks.player.PlayerService.MovePlayer:input_type -> greatestworks.player.MovePlayerRequest
	16, // 28: greatestworks.player.PlayerService.GetOnlinePlayers:input_type -> greatestworks.player.GetOnlinePlayersRequest
	5,  // 29: greatestworks.player.PlayerService.CreatePlayer:output_type -> greatestworks.player.CreatePlayerResponse
	7,  // 30: greatestworks.player.PlayerService.Login:output_type -> greatestworks.player.LoginResponse
	9,  // 31: greatestworks.player.PlayerService.Logout:output_type -> greatestworks.player.LogoutResponse
	11, // 32: greatestworks.player.PlayerService.GetPlayerInfo:output_type -> greatestworks.player.GetPlayerInfoResponse
	13, // 33: greatestworks.player.PlayerService.UpdatePlayer:output_type -> greatestworks.player.UpdatePlayerResponse
	15, // 34: greatestworks.player.PlayerService.MovePlayer:output_type -> greatestworks.player.MovePlayerResponse
	17, // 35: greatestworks.player.PlayerService.GetOnlinePlayers:output_type -> greatestworks.player.GetOnlinePlayersResponse
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_player_proto_init() }
func file_proto_player_proto_init() {
	if File_proto_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_player_proto_rawDesc), len(file_proto_player_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_player_proto_goTypes,
		DependencyIndexes: file_proto_player_proto_depIdxs,
		EnumInfos:         file_proto_player_proto_enumTypes,
		MessageInfos:      file_proto_player_proto_msgTypes,
	}.Build()
	File_proto_player_proto = out.File
	file_proto_player_proto_goTypes = nil
	file_proto_player_proto_depIdxs = nil
}
